INSERT INTO users (user_name,user_tier , user_location , top_category) VALUES
('a', 'Silver', 'jawa', 'Kosmetik'),
('b', 'Silver', 'jawa', 'Makanan'),
('c', 'Silver', 'luarjawa', 'None'),
('c2', 'Silver', 'luarjawa', 'None'),
('d', 'Silver', 'luarjawa', 'Tagihan'),
('e', 'Gold', 'jawa', 'Kosmetik'),
('f', 'Gold', 'jawa', 'Makanan'),
('g', 'Gold', 'luarjawa', 'Tagihan'),
('h', 'Gold', 'luarjawa', 'Tagihan'),
('i', 'Platinum', 'jawa', 'Kosmetik'),
('j', 'Platinum', 'jawa', 'Makanan'),
('k', 'Platinum', 'luarjawa', 'Tagihan'),
('l', 'Platinum', 'luarjawa', 'Makanan'),
('m', 'Diamond', 'jawa', 'Kosmetik'),
('n', 'Diamond', 'jawa', 'Makanan'),
('o', 'Diamond', 'luarjawa', 'Tagihan'),
('p', 'Diamond', 'luarjawa', 'Makanan')
